### PR TITLE
Generalize AP rescaling for templates.

### LINKED ISSUE #10: Rescale templates independently of AP
Missing option to rescale templates independently of the AP parameters provided. 

output_AP_template_rescaling

### PR DESCRIPTION
**Pull request by rdnv**
Check if sampling over astar: if not, use the AP parameters to determine template rescaling factor in theory_xi().

Close #10

### CODE REVIEW

**Comment by seshnadathur** [comment]
I think this might have the issue that we will always need to have `astar` as a key in `params` for compatibility with Cobaya. So it might be better to have a kwarg flag passed which controls whether to use that value of `astar` or instead compute the rescaling from the AP parameters

**Comment by rdnv** [comment]
What if I make the default -1 in the likelihood yaml file and then use a check of `if params['astar']<0: mu_integral`. That would keep us from adding too many settings that we have to keep track of.

**Comment by seshnadathur** [comment]
I don't like the workaround of having a default value of astar = -1. It makes things much less obvious to the reader/user of the code as to what is actually happening. I think it would be preferable to have a kwarg that can be passed to the function call which turns on a scaling with astar (the default being to ignore it).

**Comment by seshnadathur** [comment]
Looks fine, except for a typo in the config file which I will sort out after merging.

**Pull request merged**
